// HGVS sequence variant

// hgvs_variant = @{ g_variant | m_variant | c_variant | n_variant | r_variant | p_variant }

hgvs_variant = @{ g_variant }

g_variant = @{ accession }
// m_variant = @{ accession }
// c_variant = @{ accession }
// n_variant = @{ accession }
// r_variant = @{ accession }
// p_variant = @{ accession }

// Accessions, possibly versioned.  Should accept, e.g., `NM_01234.5`, `LRG_01234.1`.
accession = @{
    ASCII_ALPHA ~
    ASCII_ALPHANUMERIC+ ~
    ("_" ~ ASCII_ALPHANUMERIC+)? ~
    ("." ~ ASCII_DIGIT+)?
}

// An optional gene expression.
opt_gene_expr = @{ paren_gene? }
paren_gene = @{ "(" ~ gene_symbol ~ ")" }
gene_symbol = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC+ }
